### ISSUE TITLE
Timeclock: Way to select from multiple jobs

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#105]
For employees who have multiple jobs and use the badge entry system, we'll need to provide a way for them to select from the available jobs after a successful badge read action. The job selection action can utilize the touch screen for the pi. 

After selecting a job, we'll probably need a confirmation screen about the selection to provide a mechanism to undo an incorrect selection. 

This should not change the workflow for users with only one job (badge in, badge out).

**Comment by sibow** [comment]
for employee with multiple jobs, after the batch swiping, the system will offer a second screen with their jobs list in checkbox fashion and the user will pick one of them, by default the primary job will be selected so the user must click on Submit, otherwise must change the job to another one.
When the employee swipe his batch again, he will be clocked-out from the job that he previously clocked-in with. 
The second screen where the user must select one of  the jobs need styling, so Adam please take care of it.

**Comment by adabutch** [comment]
This is in place (Outlaw), closing as complete.

![out](https://user-images.githubusercontent.com/2372040/48436017-bfb9fa00-e74b-11e8-96b5-4dcaeb52cef6.gif)
