### ISSUE TITLE
Timewarp details output should render in all browsers

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#196]
Garrett Towell is unable to see time details when looking at Timewarp via the more details section. His screen shows:

![capture 1](https://user-images.githubusercontent.com/2225624/53350088-6d60ab80-38ec-11e9-8fa8-9cf6636486f5.PNG)

Which is missing important details:
<img width="1250" alt="screen shot 2019-02-25 at 9 54 57 am" src="https://user-images.githubusercontent.com/2225624/53350191-9ed97700-38ec-11e9-9c9f-efb070fc8115.png">

**Comment by charlesbrandt** [comment]
It turns out that this is a browser issue. This only happens when viewing the timewarp output in IE. Once we've moved this information into the main Time Details interface (#197), this will be moot, but in the meantime it would be nice to have markup that works in all browsers.

**Comment by sibow** [comment]
the problem was his browser when switched to firefox everything was showing

**Comment by charlesbrandt** [comment]
I'd like to keep this issue open as something to tackle for the front-end. Updated subject to better reflect the issue.

**Comment by adabutch** [comment]
I can confirm the text is being rendered on the page but for a variety of different reasons things are clashing and causing it not to show in IE 11.

This TimeWarp area is not one that I've yet dug into. I'm happy to debug/rework this area or wait for #197 ... since it's only happening in IE 11 & other alternatives exist for browsing, I'll leave this be for the moment.

**Comment by sibow** [comment]
in the new released this is changed and no need for approvers to see this any more as it will be listed
on the employee main detail page
