### ISSUE TITLE
Accrual Summary

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#78]
Please expand the acronyms.  Keep "PTOA" but call it "PTOA: Paid Time Off Accrued", "SCKA: Sick Time Accrued",  for instance.  We have enough space for this.

**Comment by schertza** [comment]
From google search: "Compensatory time, referred to as comp time, is paid time off given to a non-exempt employee instead of overtime pay."

Since "Compensatory Time" is pretty long, I'm suggesting using "Comp Time" as well. The "U" (in the abbreviation) should in should not be expanded to "Used" as well because these are the accrual banks not necessarily what was "Used".

This leaves us with something similar to these:

PTOA: "Paid Time Off Accrued"
SCKA: "Sick Time Accrued"
CUA: "Comp Time Accrued"
HCUA: "Holiday Comp Time Accrued"

**Comment by sibow** [comment]
updated
